- name: Testing loops
  hosts: all
  become: yes
  tasks:
    - user:
        name: "{{item}}"
        state: absent
      loop:
        - joe
        - george
    # - name: value loops
    #   debug:
    #     msg: "{{item}}"
    #   loop:
    #     - joe
    #     - george
